Website = "https://www.facebook.com//"
Login1 = "//button[@id='u_0_5_yl']"
Login = "//button[@id='loginbutton']"

Email = "email"
Email_send_key1 = "0918137301"
Pass = "pass"
Pass_send_key1 = "amankiya23"
Email_send_key2 = "asrete@gmmail.com"
Pass_send_key2 = "12341234"
