from selenium.webdriver.common.by import By
import time
from Facebook.Test.Base_test.Base import *
from Facebook.BaseTest.registration_locators import *

class Test(BaseTest):
    def test1_registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Fn1)
        coupon.clear()
        coupon.send_keys(Fn1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Ln1)
        coupon.clear()
        coupon.send_keys(Ln1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1)
        coupon.clear()
        coupon.send_keys(Email_1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1_confi)
        coupon.clear()
        coupon.send_keys(Email_1_confi_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Password_1)
        coupon.clear()
        coupon.send_keys(Password_1_send_key)
        coupon.click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_month1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_month1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_day1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_day1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_year1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_year1_option).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()


    def test2_registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Fn1)
        coupon.clear()
        coupon.send_keys(Fn1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Ln1)
        coupon.clear()
        coupon.send_keys(Ln1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1)
        coupon.clear()
        coupon.send_keys(Email_1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1_confi)
        coupon.clear()
        coupon.send_keys(Email_1_confi_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Password_1)
        coupon.clear()
        coupon.send_keys(Password_1_send_key)
        coupon.click()
        time.sleep(2)
        driver.find_element(By.XPATH, Gender1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()


    def test_3registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Fn1)
        coupon.clear()
        coupon.send_keys(Fn1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Ln1)
        coupon.clear()
        coupon.send_keys(Ln1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1)
        coupon.clear()
        coupon.send_keys(Email_1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1_confi)
        coupon.clear()
        coupon.send_keys(Email_1_confi_send_key)
        time.sleep(2)
        driver.find_element(By.NAME, Bd_month1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_month1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_day1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_day1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_year1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_year1_option).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Gender1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()


    def test_4registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Fn1)
        coupon.clear()
        coupon.send_keys(Fn1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Ln1)
        coupon.clear()
        coupon.send_keys(Ln1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1)
        coupon.clear()
        coupon.send_keys(Email_1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Password_1)
        coupon.clear()
        coupon.send_keys(Password_1_send_key)
        coupon.click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_month1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_month1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_day1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_day1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_year1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_year1_option).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Gender1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()


    def test_5registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Fn1)
        coupon.clear()
        coupon.send_keys(Fn1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Ln1)
        coupon.clear()
        coupon.send_keys(Ln1_send_key)
        time.sleep(2)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1_confi)
        coupon.clear()
        coupon.send_keys(Email_1_confi_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Password_1)
        coupon.clear()
        coupon.send_keys(Password_1_send_key)
        coupon.click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_month1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_month1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_day1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_day1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_year1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_year1_option).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Gender1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()


    def test6_registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Fn1)
        coupon.clear()
        coupon.send_keys(Fn1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1)
        coupon.clear()
        coupon.send_keys(Email_1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1_confi)
        coupon.clear()
        coupon.send_keys(Email_1_confi_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Password_1)
        coupon.clear()
        coupon.send_keys(Password_1_send_key)
        coupon.click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_month1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_month1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_day1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_day1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_year1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_year1_option).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Gender1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()


    def test7_registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Ln1)
        coupon.clear()
        coupon.send_keys(Ln1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1)
        coupon.clear()
        coupon.send_keys(Email_1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1_confi)
        coupon.clear()
        coupon.send_keys(Email_1_confi_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Password_1)
        coupon.clear()
        coupon.send_keys(Password_1_send_key)
        coupon.click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_month1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_month1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_day1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_day1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_year1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_year1_option).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Gender1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()


    def test8_registration(self):
        driver = super().test_init()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin_button).click()
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Fn1)
        coupon.clear()
        coupon.send_keys(Fn2_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Ln1)
        coupon.clear()
        coupon.send_keys(Ln1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1)
        coupon.clear()
        coupon.send_keys(Email_1_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Email_1_confi)
        coupon.clear()
        coupon.send_keys(Email_1_confi_send_key)
        time.sleep(2)
        coupon = driver.find_element(By.NAME, Password_1)
        coupon.clear()
        coupon.send_keys(Password_1_send_key)
        coupon.click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_month1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_month1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_day1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_day1_option).click()
        time.sleep(2)
        driver.find_element(By.NAME, Bd_year1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Bd_year1_option).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Gender1).click()
        time.sleep(2)
        driver.find_element(By.XPATH, Signin).click()
        time.sleep(5)
        super().tear_down()




